### ISSUE TITLE
Freq monthly with BYDAY=+3TU cause IndexError: tuple index out of range

### ISSUE THREAD

**Issue by Eluminae** [jspricke/python-remind#14] opened 2021-03-08 18:40 UTC
Hello there,

Thanks a lot for you works on this !

I wanna report a bug I'm facing using dav2rem.

```
Traceback (most recent call last):
  File "/home/stacy/.local/bin/dav2rem", line 8, in <module>
    sys.exit(main())
  File "/home/stacy/.local/lib/python3.9/site-packages/dav2rem.py", line 84, in main
    rem.append_vobject(readOne(vevent.data))
  File "/home/stacy/.local/lib/python3.9/site-packages/remind.py", line 485, in append_vobject
    outdat = self.to_reminders(ical)
  File "/home/stacy/.local/lib/python3.9/site-packages/remind.py", line 472, in to_reminders
    reminders = [self.to_remind(vevent, label, priority, tags, tail, sep,
  File "/home/stacy/.local/lib/python3.9/site-packages/remind.py", line 472, in <listcomp>
    reminders = [self.to_remind(vevent, label, priority, tags, tail, sep,
  File "/home/stacy/.local/lib/python3.9/site-packages/remind.py", line 403, in to_remind
    trigdates = Remind._parse_rruleset(vevent.rruleset)
  File "/home/stacy/.local/lib/python3.9/site-packages/remind.py", line 327, in _parse_rruleset
    rep.append('%d' % rruleset._rrule[0]._bymonthday[0])
IndexError: tuple index out of range
```

It seems that `rruleset._rrule[0]._bymonthday` is empty in this case

printing the `rruleset._rrule[0]` gives me `RRULE:FREQ=MONTHLY;INTERVAL=3;BYDAY=+3TU`

**Comment by jspricke** [comment] 2021-03-08 20:51
I cannot reproduce this, which version of python-remind do you use? Can you paste the full event (with private data redacted)?

**Comment by jspricke** [comment] 2021-03-08 21:10
Seems like this was fixed in https://github.com/jspricke/python-remind/commit/7321e5d8158797f8aa65a2b1d2aa0507039a5bcf, can you try?

**Comment by Eluminae** [comment] 2021-03-08 22:28
oh right ! It seems to be related to my issue.

I use the 0.15 wich seems to be released the Jul 25 2020 wich precede the commit date

Does it feels possible to release anytime soon ?

**Comment by jspricke** [comment] 2021-03-10 12:40
I've released v0.16.0 including the fix.

**Closed by jspricke** 2021-03-10 12:40 UTC
